/** @type {import('tailwindcss').Config} */
// Single source of truth for the design system - every screen pulls colors,
// fonts and spacing from here instead of hardcoding hex values in components.
// Tokens lifted 1:1 from the approved Stitch mockup so every screen stays
// visually consistent with it.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#62ff96",
        background: "#111318",
        error: "#ffb4ab",
        "surface-container-low": "#1a1c20",
        "inverse-surface": "#e2e2e8",
        "on-primary-fixed": "#001f28",
        "on-error-container": "#ffdad6",
        "surface-container": "#1e2024",
        "secondary-container": "#7508a5",
        "primary-fixed-dim": "#4cd6ff",
        outline: "#859399",
        "surface-bright": "#37393e",
        "on-surface": "#e2e2e8",
        "on-error": "#690005",
        "on-secondary-container": "#e19fff",
        "on-secondary-fixed-variant": "#7201a2",
        "on-primary-container": "#00566a",
        "on-tertiary-fixed": "#00210b",
        "error-container": "#93000a",
        "inverse-on-surface": "#2f3035",
        "on-secondary": "#510074",
        "primary-container": "#00d1ff",
        "inverse-primary": "#00677f",
        surface: "#111318",
        "tertiary-fixed-dim": "#00e475",
        "surface-container-high": "#282a2e",
        "secondary-fixed": "#f6d9ff",
        "surface-container-highest": "#333539",
        "on-tertiary-container": "#005b2b",
        "on-secondary-fixed": "#310048",
        "surface-dim": "#111318",
        "surface-variant": "#333539",
        "outline-variant": "#3c494e",
        "tertiary-container": "#00dd71",
        "secondary-fixed-dim": "#e8b3ff",
        secondary: "#e8b3ff",
        "on-surface-variant": "#bbc9cf",
        primary: "#a4e6ff",
        "surface-container-lowest": "#0c0e12",
        "on-primary": "#003543",
        "on-primary-fixed-variant": "#004e60",
        "primary-fixed": "#b7eaff",
        "surface-tint": "#4cd6ff",
        "on-tertiary": "#003918",
        tertiary: "#39fb88",
        "on-tertiary-fixed-variant": "#005226",
        "on-background": "#e2e2e8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-padding": "24px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "display-lg": ["Inter"],
        "data-mono-sm": ["JetBrains Mono"],
        "body-base": ["Inter"],
        "data-mono-lg": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
